name: Publication du package sur NPM
permissions:
  id-token: write # Pour permettre le --provenance de la publication npm https://docs.npmjs.com/generating-provenance-statements#publishing-packages-with-provenance-via-github-actions
  contents: read

on:
  release:
    types: [published]

jobs:
  publication:
    runs-on: ubuntu-latest

    steps:
      - name: Git checkout
        uses: actions/checkout@v6

      - name: Récupérer la version
        run: echo "release_version=$(node -p "require('./package.json').version")" >> $GITHUB_ENV

      - name: Installer Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24
          registry-url: "https://registry.npmjs.org/"
          package-manager-cache: false

      - name: Installer les dépendances
        run: npm install -g "$(jq -r '.packageManager' package.json)" && pnpm install

      - name: Exécuter les tests
        run: pnpm run test

      - name: Builder le package
        run: pnpm run build

      - name: Publier sur NPM
        run: pnpm publish --provenance --access public --no-git-checks
